let title=document.getElementById("title"),price=document.getElementById("price"),texes=document.getElementById("texes"),ads=document.getElementById("ads"),discount=document.getElementById("discount"),total=document.getElementById("total"),count=document.getElementById("count"),category=document.getElementById("category"),submit=document.getElementById("submit"),mood="create",temp;function getTotal(){if(""!=price.value){let t=+price.value+ +texes.value+ +ads.value-discount.value;total.innerHTML=t,total.style.backgroundColor="rgba(0, 0, 0, 0.2)",total.style.border="0.5px solid #333",total.style.color="#fff"}else total.innerHTML="",total.style.backgroundColor="rgb(143, 59, 59)",total.style.border="0.5px solid #fff",total.style.color="#fff"}let dataproduct=[];function clearData(){title.value="",price.value="",texes.value="",ads.value="",discount.value="",count.value="",category.value="",total.innerHTML=""}function showdata(){let t="";for(let e=0;e<dataproduct.length;e++)t+=` <div class="card"> 
    <hr class="split">
    <h2 style="color: #eee">اسم المنتج <hr class="split2"></h2>
    <h4>${dataproduct[e].title}</h4> 
    <br><h2 style="color: #eee"> الفئة  <hr class="split2"></h2>
    <h4>${dataproduct[e].category}</h4> 
    <br><h2 style="color: #eee"> السعر   <hr class="split2"></h2> 
    <h4>${dataproduct[e].total}</h4> 
<button class="edit"><li class="fas fa-edit" style="font-size:20px;color:rgb(26,90,193)" onclick="updatedata(${e})"></li> </button>   
<button class="delete"><li class="fas fa-trash" style="font-size:20px;color:#ca261d" onclick="deletedata(${e})"></li> </button></div>`;document.getElementById("thebody").innerHTML=t,dataproduct.length<1&&(document.getElementById("thebody").innerHTML+="<div style='text-align:center;margin:auto'><img src='./no-product.gif' class='no-product' /> <br><br><br><h1 style='color:#E3163E'>لا توجد منتجات مضافة حتى الآن</h1></div>")}function deletedata(t){confirm("Are You Sure?")&&(dataproduct.splice(t,1),localStorage.product=JSON.stringify(dataproduct),showdata())}function updatedata(t){title.value=dataproduct[t].title,price.value=dataproduct[t].price,texes.value=dataproduct[t].texes,ads.value=dataproduct[t].ads,discount.value=dataproduct[t].discount,category.value=dataproduct[t].category,getTotal(),count.style.display="none",submit.innerHTML="تحديث",mood="update",temp=t}null!=localStorage.product&&(dataproduct=JSON.parse(localStorage.product)),submit.onclick=function(){let t={title:title.value.toLowerCase(),price:price.value,texes:texes.value,ads:ads.value,discount:discount.value,total:total.innerHTML,count:count.value,category:category.value.toLowerCase()};if(""!==title.value&&""!==price.value&&""!==texes.value&&""!==ads.value&&""!==discount.value&&""!==category.value&&t.count<100){if("create"===mood){if(t.count>1){for(i=0;i<t.count;i++)dataproduct.push(t);clearData()}else dataproduct.push(t),clearData()}else dataproduct[temp]=t,mood="create",submit.innerHTML="إضافة",count.style.display="block";clearData(),showdata()}localStorage.setItem("product",JSON.stringify(dataproduct)),showdata()},showdata();let searchmood="title";function getsearch(t){let e=document.getElementById("search");"searchtitle"==t&&(searchmood="title",e.placeholder="Search By Title"),e.focus(),e.value="",showdata()}function searchdata(t){let e="";if("title"==searchmood)for(let a=0;a<dataproduct.length;a++)dataproduct[a].title.toLowerCase().includes(t.toLowerCase())&&(e+=`<div class="card"> 
    <hr class="split">
    <h2 style="color: #eee">اسم المنتج <hr class="split2"></h2>
    <h4>${dataproduct[a].title}</h4> 
    <br><h2 style="color: #eee"> الفئة  <hr class="split2"></h2>
    <h4>${dataproduct[a].category}</h4> 
    <br><h2 style="color: #eee"> السعر   <hr class="split2"></h2> 
    <h4>${dataproduct[a].total}</h4> 
<button class="edit"><li class="fas fa-edit" style="font-size:20px;color:rgb(26,90,193)" onclick="updatedata(${a})"></li> </button>   
<button class="delete"><li class="fas fa-trash" style="font-size:20px;color:#ca261d" onclick="deletedata(${a})"></li> </button></div>`);document.getElementById("thebody").innerHTML=e}